### ISSUE TITLE
Function calculateDistance accepts non-numeric values

### ISSUE THREAD

**Issue by RituDebug** [perfectprofesionist/geo-location-calculator#1]
I have noticed that the **calculateDistance** function in the **codebase** is not handling non-numeric input values properly. When non-numeric values are passed for latitude and longitude, the function proceeds without validating them, which may lead to unexpected behavior.

**Steps to Reproduce:**
1. Use the calculateDistance function with non-numeric values for latitude and/or longitude.
2. Observe that the function does not throw an exception for non-numeric values.

**Expected Behavior:**
The function should validate input values and throw an exception if any of them is not a number.

**Actual Behavior:**
The function does not validate input values, allowing non-numeric values to be processed without any warning.

**Comment by perfectprofesionist** [comment]
Thank you for bringing this to our attention. The issue has been addressed, and the calculateDistance function now properly validates input values for latitude and longitude. If non-numeric values are provided, the function will throw an exception, ensuring better handling of invalid input. Feel free to test it again, and let us know if you encounter any further issues. Your feedback is valuable to us!
